DROP TABLE IF EXISTS MEMBER CASCADE;
creare TABLE MEMBER
(
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	userid varchar(255) NOT NULL,
	pw varchar(255) NOT NULL,
	roles varchar(255) NOT NULL,
	PRIMARY KEY (id),
	unique(userid)
)